version: '3'
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=puzzle
      - MYSQL_USER=puzzle
      - MYSQL_PASSWORD=puzzle
      - MYSQL_DATABASE=puzzle
    volumes:
      - "./scripts/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./sql:/sql"
